// This file is generated by Convex. Do not edit manually.

export function defineTable(schema) {
  return schema;
}

export function defineIndex(index) {
  return index;
}

export function defineFunction(func) {
  return func;
}

export function defineQuery(query) {
  return query;
}

export function defineMutation(mutation) {
  return mutation;
}

export function defineAction(action) {
  return action;
}

export function defineSchema(schema) {
  return schema;
}

export function defineTableSchema(schema) {
  return schema;
}

export function defineIndexSchema(schema) {
  return schema;
}

export function defineFunctionSchema(schema) {
  return schema;
}

export function defineQuerySchema(schema) {
  return schema;
}

export function defineMutationSchema(schema) {
  return schema;
}

export function defineActionSchema(schema) {
  return schema;
}

export function defineSchemaSchema(schema) {
  return schema;
}